# Generated by Django 4.1.5 on 2023-01-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='created_at',
        ),
    ]
