# Generated by Django 4.1.5 on 2023-01-23 13:17

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_message_message_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
