# Generated by Django 4.1.5 on 2023-01-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
    ]
