# Generated by Django 4.1.5 on 2023-01-23 13:29

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
